feat: traverse symlinks in the workspace
likec4/likec4 pull request #1213
Opened 2024-11-06 18:31 UTC by hubertmis

A likeC4 workspace can contain symbolic links to documents shared between multiple workspaces. The WorspaceManager is enhanced to traverse through symbolic links to correctly include documents linked by symbolic links.

2024-11-06 19:01 UTC, hubertmis commented
@davydkov , do you have any hints why playground can't find the node:fs module?

2024-11-06 21:25 UTC, davydkov requested changes
Hey @hubertmis 

I see what you're trying to solve, but you did not take into account that language server (and vscode extension) can be run as webworker in browser (and playground does it), and thus `node:fs` is not available there.

Check:
- `startLanguageServer` in node runtime, [index.ts](https://github.com/likec4/likec4/blob/ee04db787862985c1b723cefea6cd6f1db4857ec/packages/language-server/src/index.ts#L2) langium provided with `NodeFileSystem`
- `startLanguageServer` in browser [browser.ts](https://github.com/likec4/likec4/blob/main/packages/language-server/src/browser.ts)

I suggest you provide node runtime only implementation via dependency-injection (like `WorkspaceCrawler.ts`)
Later, we may want to configure it, turn on/off resolving symlinks, add `includes/excludes` (as in recent [discussion #1174](https://github.com/likec4/likec4/discussions/1174))
[`fdir`](https://github.com/thecodrr/fdir) seems a perfect fit.

Or consider to override [`NodeFileSystem`](https://github.com/eclipse-langium/langium/blob/main/packages/langium/src/node/node-file-system-provider.ts) and traverse symlinks there?

And don't forget about [CLI](https://github.com/likec4/likec4/blob/ee04db787862985c1b723cefea6cd6f1db4857ec/packages/likec4/src/language/module.ts#L142) (also initialised with `NodeFileSystem`)

2024-11-06 21:25 UTC, davydkov commented on packages/language-server/src/shared/WorkspaceManager.ts
> +    const stat = await fs.promises.lstat(uri.fsPath)
This is redundant call, as  `includeEntry` does `lstatSync`

2024-11-06 21:42 UTC, hubertmis commented
Thanks for the hints! I'll have a look at the modules you suggested

2024-11-06 22:52 UTC, hubertmis commented
I don't know what "dependency-injection" is and I could not find the `WorkspaceCrawler.ts` example. However, traversing symlinks in overridden `NodeFileSystem` seemed clear enough for me. It seems to work fine!

2024-11-08 23:43 UTC, davydkov approved these changes
>  I could not find the WorkspaceCrawler.ts example

Sorry, I was not clear, I mean create new file and name it like `WorkspaceCrawler.ts`

I merge this PR, and I move `LikeC4FileSystem` out of `index.ts`

2024-11-08 23:43 UTC, merged